main: exercises solutions

exercises:
	pdflatex main
	pdflatex main

solutions:
	pdflatex solutions
	pdflatex solutions

clean:
	rm -f main.pdf main.aux main.bbl main.blg main.log mainNotes.bib
	rm -f solutions.pdf solutions.aux solutions.bbl solutions.blg solutions.log solutionsNotes.bib
